# Generated by Django 3.2.12 on 2022-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
